### ISSUE TITLE
Passing query params into gql

### ISSUE THREAD

**Issue by Kenneth-13** [sisense/graphql2rest#21]
Hi

I was trying to pass some parameters to gql through REST and my schema looks like this:
`
type Query{
foo(paramA : typeA, paramB: typeB) : returnType!
`

Here typeA is defined as 
`input typeA {
    key: String
    value: String
    operation: String
    }
`
I need to pass key, value and operation as query parameters 

What I tried:
Using a middleware function that modifies the query params to the required format.

`const middlewareFunc = (req, route, verb, operation) => {
    if (req.query.key && req.query.value && req.query.operation) {
        req.query = { paramA : {key : req.query.key, value : req.query.value, operation : req.query.operation } };
    }
}`

The parameters aren't being passed down to GQL as expected
Can anyone help me on this, it be of great help.
Thanks in advance

**Comment by roy-mor** [comment]
I'd like to try and help. First, your graphql2rest middleware function doesn't return anything. You'd need to return `req` (after modifying it), in order for the modified request to propagate down to GraphQL. Secondly, you are mutating `req.query`, which is the query string object. You might want to update `req.body` with the expected parameters, then delete those fields on `req.query`. 

Let me know if that fixed that issue. 

If not, please include the debug log from graphql2rest, since it will show what was received from REST and what was passed to the GraphQL layer, and whether the middleware function was invoked at all. Also, please include full, indented code snippets that are easier to read.

**Comment by Kenneth-13** [comment]
Hey thanks for the quick reply

I was returning `req` and also exporting it using `module.exports = { middlewareFunc };`
Now the middlewareFunc looks like this.

`````
consts middlewareFunc = (req, route, verb, operation) => {
    if (req.query.key && req.query.value && req.query.operation) {
        req.body = {
            paramA: {
                key: req.query.key,
                value:  req.query.value,
                operation: req.query.operation
            }
        };
    req.query = {}
    return req;
};
module.exports = { middlewareFunc };
`````

Debug log from graphql2rest
It seems to me that the middleware function was invoked successfully

``````
debug: REST router was invoked: route GET <rest endpoint>
debug: Actual path: <rest endpoint>
debug: Executing <query-foo> with parameters:
debug: 
{
    "paramA": {
        "key": <key-passed>,
        "value": <value-passed>,
        "operation": <operation-passed>
    }
}
debug: [Original (unformatted and unfiltered) response from GraphQL]:
``````

Here is a similar implementation of the Query I was working on.
https://api.spacex.land/graphql/
Here is the REST counterpart of the link
( https://api.spacex.land/rest/#/default/capsulesQuery )

In the query `capsules` there is a parameter `find` (paramA in my case) with which I can pass in any of the fields in `CapsulesFind` (typeA in my case) and get a filtered response.

``````
{
  capsules(find: {id:"C105"}){
    id
    landings
    missions {
      flight
      name
    }
  }
}
``````

The above query returns

``````
{
  "data": {
    "capsules": [
      {
        "id": "C105",
        "landings": 1,
        "missions": [
          {
            "flight": 14,
            "name": "CRS-3"
          }
        ]
      }
    ]
  }
}
``````

I wanted to do a REST call like `https://api.spacex.land/rest/capsules?id=C105` which would return a filtered response.
I was hoping to achieve this by changing the structure of `key`, `value` and `operation` passed as query parameters, which is needed to filter the response in my case and pass it to my query `foo` by encompassing it in `paramA`

**Comment by roy-mor** [comment]
Thanks @Kenneth-13. I'd be able to look into it later. 

In the meantime can you please share your manifest file (or at least the relevant endpoint definition in the manifest file)? 

What is the response you're getting from GraphQL server (or what's wrong with it)? 

Also it's a good idea to add some console or log prints to `middlewareFunc()` just for debugging, to see that the function was called and the if condition satisfied (you can print req.query).

**Comment by roy-mor** [comment]
I took a look now. It looks OK to me, as in, it should work, although your middleware function ignores `paramB` which could also be passed along with `paramA`, but you are overwriting it. In the debug log you provided it shows that the values passed in the REST query parameter were encapsulated correctly inside a `typeA` object before being passed to the GraphQL query. 

So what is wrong? 

If it's still not working, please provide the error or response from the GraphQL server (obfuscate details if needed) so we can see what went wrong. Thanks. 

@Kenneth-13

**Comment by Kenneth-13** [comment]
I'm hitting the query like:
``````
/api/systems?key=<some-key>&value=<some-value>&operation=<some-operation>
``````
The following is the endpoint in my manifest file

``````
		"/<endpoint>": {
			"get": {
				"operation": foo,
				"requestMiddlewareFunction" : "middlewareFunc"
			}
		}
``````

There is no error from GraphQL as such.
The response is the same as what we would expect if no parameters are passed with no filtering.

**Comment by Kenneth-13** [comment]
I'm hitting the query like:

/api/end-point?key=<some-key>&value=<some-value>&operation=<some-operation>
The following is the endpoint in my manifest file

		"/<endpoint>": {
			"get": {
				"operation": foo,
				"requestMiddlewareFunction" : "middlewareFunc"
			}
		}
There is no error from GraphQL as such.
The response is the same as what we would expect if no parameters are passed with no filtering.

**Comment by Kenneth-13** [comment]
Hey @roy-mor 
It seems like there was a mistake on my end.
It is working perfectly fine :)
Thanks again and sorry for wasting your time.

**Comment by roy-mor** [comment]
No problem @Kenneth-13 :)
We know this feature is working well, but still wanted to help you out. I'm glad it worked out for you. All the best!
