### ISSUE TITLE
Rest API document 

### ISSUE THREAD

**Issue by degarajesh** [sisense/graphql2rest#22]
Hey is there a support for rest api doc ?

If it is there can you please share samples?

**Comment by roy-mor** [comment]
Hi, what do you mean by "REST API doc"? Please elaborate.

**Comment by degarajesh** [comment]
Thank you for the quick reply, I want to expose All the APIs in a document where consumer can use it referring to the document, in sofa-api I see that they are using swagger is there something like that here, basically consumers should be able to see what are all Available get and post operations and all the available query Parms and also requests and responses.

**Comment by roy-mor** [comment]
We currently don't have support for Swagger auto-generation, although this feature is planned to be added in the future. 

You can manually generate your own Swagger/OpenAPI documentation (yaml file) based on the manifest file and the expected parameters and responses of your GraphQL queries.
