### ISSUE TITLE
Is this repo being maintained?

### ISSUE THREAD

**Issue by jiteshmanglani** [sisense/graphql2rest#80]

**Comment by roy-mor** [comment]
@jiteshmanglani Yes. What do you need done?

**Comment by jiteshmanglani** [comment]
@roy-mor, I was trying to choose library. I saw no new release or commits. So I thought it is not being maintained. Thanks for your prompt reply.

**Comment by roy-mor** [comment]
@jiteshmanglani Got it. Honestly it could be better maintained. But it is attended to when needed, some or most of the time

**Comment by jiteshmanglani** [comment]
I will try to contribute to this project.
